version: "3.3"
services:
  database:
    image: "postgres:13-alpine3.15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/dbdata/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]

  run:
      build: .
      depends_on:
        - database
      ports:
        - "12345:12345"
